### ISSUE TITLE
XmlSlurper is too strict when reading POM files for license report

### ISSUE THREAD

**Issue by theseion** [vlsi/vlsi-release-plugins#43]
Gradle: 7.0.2
License report plugin: 1.74
Problematic dependency: istack-commons-3.0.11.pom

This happens out of the box, no configuration.

```
Caused by: org.gradle.api.GradleException: The prefix "Xlint" for element "Xlint:all" is not bound.
	at com.github.vlsi.gradle.license.GatherLicenseTask.findPomLicenses(GatherLicenseTask.kt:546)
	at com.github.vlsi.gradle.license.GatherLicenseTask.run(GatherLicenseTask.kt:332)
...
	Suppressed: org.xml.sax.SAXParseException; systemId: file://<redacted>/.gradle/caches/modules-2/files-2.1/com.sun.istack/istack-commons/3.0.11/b1b7e589e116b7db7217cc2098223185690e740b/istack-commons-3.0.11.pom; lineNumber: 408; columnNumber: 38; The prefix "Xlint" for element "Xlint:all" is not bound.
...
at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1251)
at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
at groovy.util.XmlSlurper.parse(XmlSlurper.java:203)
at groovy.util.XmlSlurper.parse(XmlSlurper.java:221)
at com.github.vlsi.gradle.license.PomLicenseLoaderKt.parseXml(PomLicenseLoader.kt:111)
at com.github.vlsi.gradle.license.PomLicenseLoaderKt.access$parseXml(PomLicenseLoader.kt:1)
at com.github.vlsi.gradle.license.PomLicenseLoaderKt$loadLicenses$1$1$1$1.invokeSuspend(PomLicenseLoader.kt:139)
...
```

**Comment by DreierF** [comment]
I'm running into the same issue with `com.sun.xml.ws:policy:2.7.10` ([Link](https://repo1.maven.org/maven2/com/sun/xml/ws/policy/2.7.10/policy-2.7.10.pom)) and `com.sun.xml.ws:project:2.3.3`.
