### ISSUE TITLE
Problems when publishing calcite to the private maven nexus repo

### ISSUE THREAD

**Issue by cshuo** [vlsi/vlsi-release-plugins#44]
Hi, I want to publish a custom Calcite to a private maven repo, and the url of the repo is "http://mvnrepo.xxx.com/nexus".
I've added the following nexus configuration to `releaseParams` in `build.gradle.kts` file: 
```
nexus {
        prodUrl.set(uri("http://mvnrepo.xxx.com/nexus"))
        testUrl.set(uri("http://mvnrepo.xxx.com/nexus"))
        packageGroup.set("org.apache.calcite")
}
```
When I run the publish command `./gradlew publish`, the following exception arose
```
Caused by: org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not PUT 'http://mvnrepo.xxx.com/content/repositories/snapshots/org/apache/calcite/calcite-babel/1.30.1-ververica-test-SNAPSHOT/maven-metadata.xml'. Received status code 404 from server: Not found
```
I noticed that the prefix of the url is `http://mvnrepo.xxx.com/` rather than `http://mvnrepo.xxx.com/nexus/`, the keyword 'nexus' is just omitted somehow. I'm not sure whether it's because I missed some configuration or there is something wrong in the plugin, any help is appreciated, thanks.

**Comment by cshuo** [comment]
@vlsi would you please have a look

**Comment by vlsi** [comment]
Hi, could you please try https://gist.github.com/vlsi/8daf6cc64c91d1d59e899caa13dd18dc ?

It might already work for you, however, it requires adding an init script on the builder machine.

---

The bug seems to be at https://github.com/vlsi/vlsi-release-plugins/blob/13a41fd946c9f65228b6870aa3437f2b041e55da/plugins/stage-vote-release-plugin/src/main/kotlin/com/github/vlsi/gradle/release/StageVoteReleasePlugin.kt#L569-L570 , and it looks like `replacePath` does what it looks like: it replaces the path instead of adding the relevant subpath.

**Comment by cshuo** [comment]
@vlsi Thanks for reply. I've try https://gist.github.com/vlsi/8daf6cc64c91d1d59e899caa13dd18dc, but another exception arose.
I've create an script `$HOME/.gradle/init.gradle.kts` like the following:
```
allprojects {
    plugins.withId("maven-publish") {
        configure<PublishingExtension> {
            repositories {
                maven {
                    name = "secretNexus"
                    val baseUrl = "http://mvnrepo.alibaba-inc.com/nexus"
                    val releasesUrl = "$baseUrl/repository/maven-releases"
                    val snapshotsUrl = "$baseUrl/repository/maven-snapshots"
                    val release = !project.version.toString().endsWith("-SNAPSHOT")
                    url = uri(if (release) releasesUrl else snapshotsUrl)
                    credentials {
                        username = "xxx"
                        password = "xxx"
                    }
                }
            }
        }
     }
}
```
After I run command: `./gradlew publishAllPublicationsToSecretNexusRepository`, I got the following exception, and I failed to find any effective solution after searching...
```
 Caused by: org.codehaus.plexus.util.xml.pull.XmlPullParserException: end tag name </head> must be the same as start tag <meta> from line 6 (position: TEXT seen ...s?74" rel="preload" as="script" crossorigin="anonymous"/>\r\n</head>... @8:8) 
                    at org.codehaus.plexus.util.xml.pull.MXParser.parseEndTag(MXParser.java:2098)
                    at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1359)
                    at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1317)
                    at org.apache.maven.artifact.repository.metadata.io.xpp3.MetadataXpp3Reader.checkUnknownElement(MetadataXpp3Reader.java:121)
                    at org.apache.maven.artifact.repository.metadata.io.xpp3.MetadataXpp3Reader.parseMetadata(MetadataXpp3Reader.java:854)
                    at org.apache.maven.artifact.repository.metadata.io.xpp3.MetadataXpp3Reader.read(MetadataXpp3Reader.java:1189)
                    at org.apache.maven.artifact.repository.metadata.io.xpp3.MetadataXpp3Reader.read(MetadataXpp3Reader.java:1122)
                    at org.apache.maven.artifact.repository.metadata.io.xpp3.MetadataXpp3Reader.read(MetadataXpp3Reader.java:1151)
                    at org.gradle.api.publish.maven.internal.publisher.AbstractMavenPublisher.lambda$readExistingMetadata$1(AbstractMavenPublisher.java:137)
                    at org.gradle.internal.resource.transfer.AccessorBackedExternalResource.withContentIfPresent(AccessorBackedExternalResource.java:113)
                    at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$10.call(BuildOperationFiringExternalResourceDecorator.java:221)
                    at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$10.call(BuildOperationFiringExternalResourceDecorator.java:213)
                    at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
                    at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
                    at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
                    at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
                    at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
                    at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
                    at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
                    at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator.withContentIfPresent(BuildOperationFiringExternalResourceDecorator.java:213)
                    at org.gradle.api.publish.maven.internal.publisher.AbstractMavenPublisher.readExistingMetadata(AbstractMavenPublisher.java:135)
                    at org.gradle.api.publish.maven.internal.publisher.MavenRemotePublisher.getNextBuildNumber(MavenRemotePublisher.java:106)
                    at org.gradle.api.publish.maven.internal.publisher.MavenRemotePublisher.createSnapshotMetadata(MavenRemotePublisher.java:75)
                    at org.gradle.api.publish.maven.internal.publisher.AbstractMavenPublisher.publish(AbstractMavenPublisher.java:68)
                    at org.gradle.api.publish.maven.internal.publisher.MavenRemotePublisher.publish(MavenRemotePublisher.java:61)
                    at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher.publish(ValidatingMavenPublisher.java:50)
                    at org.gradle.api.publish.maven.tasks.PublishToMavenRepository$1.publish(PublishToMavenRepository.java:110)
                    at org.gradle.api.publish.internal.PublishOperation.run(PublishOperation.java:43)

```

**Comment by vlsi** [comment]
> XmlPullParserException: end tag name </head> must be the same as start tag <meta> from line 6 (position: TEXT seen ...s?74" rel="preload" as="script" crossorigin="anonymous"/>\r\n</head>

It looks like the repository returns HTML response which could happen in two cases:
a) You use the wrong URL
b) You use the wrong credentials

**Comment by cshuo** [comment]
@vlsi Thanks. You're right, the URL in my script is wrong. Now it works. 👍
